name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pipx install poetry
      - name: Configure Poetry to not create venvs in project
        run: poetry config virtualenvs.in-project true
      - name: Install deps
        run: poetry install --no-interaction --no-root
      - name: Run tests
        run: poetry run pytest -q
